name: Buf CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  buf:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Install buf CLI
      - uses: bufbuild/buf-setup-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Lint
        run: buf lint proto

      - name: Build
        run: buf build proto

      # Compares the current branch against main's proto/ for breaking changes.
      # On a brand-new repo (no main yet), this will print a note and continue.
      - name: Breaking check against main
        if: github.ref != 'refs/heads/main'
        run: |
          buf breaking proto --against '.git#branch=main,subdir=proto' \
          || echo "Skipping breaking-check (likely first run or main not present)."

  roundtrip:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: bufbuild/buf-setup-action@v1

      - name: Generate code
        run: buf generate proto

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: pip install protobuf>=6.32.0,<7

      - name: Run round-trip tests
        run: PYTHONPATH=gen/python python tests/roundtrip/python_roundtrip.py
